### ISSUE TITLE
The admin becomes very slow if an API has many REST services that have fields

### ISSUE THREAD

**Issue by pietervogelaar** [zfcampus/zf-apigility-admin#203]
I have an API with 20 REST services. Each service has about 10 fields defined.
If I click in the fields tab of a REST service on EDIT it makes my browser hang for 20 seconds. The behaviour is the same in the latest firefox and chrome version. 

I have a fast ubuntu workstation with 10GB RAM.

**Comment by spectravp** [comment]
An update to this: Apigility isn't taking advantage of the "track by" feature of ng-repeat. Could be an oversight, or it could be that the track by functionality wasn't available in the version of angular used during development. However, I can confirm that adding track by to the ng-repeats improves performance 100 fold.  The DOM is being manipulated way too much without this and keep in mind that each ng-repeat item gets its own scope. And by default it is $watch'ing the whole object, so if you change a property of that object, the entire ng-repeat scope is $digested. Instead, the ng-repeat should be tracking a property. From the angular docs:

"If you are working with objects that have an identifier property, you can track by the identifier instead of the whole object. Should you reload your data later, ngRepeat will not have to rebuild the DOM elements for items it has already rendered, even if the JavaScript objects in the collection have been substituted for new ones"

**Comment by ezimuel** [comment]
This issue should be fixed by Apigility 1.1.0
