### ISSUE TITLE
Documentation page empty due to JS errors

### ISSUE THREAD

**Issue by codeaid** [zfcampus/zf-apigility-admin#278]
Documentation page for an API (created previously using Apigility 1.0.4) does not load due to javascript errors on the page:

![Admin bug](http://s23.postimg.org/x6ng2u6aj/zf_apigility_admin_bug.png)

I did manage to update description of an RPC service in its Documentation tab. Generated contents of `documentation.config.php` are as follows:

```php
<?php
return [
    'Api\\V1\\Rpc\\MyService\\Controller' => [
        'description' => 'Description of my service',
    ],
];
```

The page makes a `GET` request to `/apigility/documentation`, which returns the following JSON:

```json
[{"name":"Api","versions":["1"]}]
```

So it looks like it's not even including the documentation in the response.

**Comment by weierophinney** [comment]
This is fixed with the combination of zfcampus/zf-apigility-documentation#27 and zfcampus/zf-apigility-admin-ui#36 ; if you run `composer update zfcampus/zf-apigility-documentation zfcampus/zf-apigility-admin-ui` from your project root, you will pick up new versions of these modules that correct the issue.
