### ISSUE TITLE
The db autodiscover doesn't work for ibmdb2 adapter

### ISSUE THREAD

**Issue by ezimuel** [zfcampus/zf-apigility-admin#304]
The db-connected feature on **ibmdb2** adapter doesn't work, because the DB autodiscover feature throws an Exception [here](https://github.com/zendframework/zend-db/blob/master/src/Metadata/Metadata.php#L60). We need to manage the Exception and provide the db-connected option without the metadata support, until we will implement a Metadata adapter for ibmdb2.

**Comment by ezimuel** [comment]
Fixed in #305.

**Comment by Naktibalda** [comment]
Since I raised a [related issue](https://github.com/zfcampus/zf-apigility-admin/issues/364), I would like to update this ticket:
The link provided in the ticket is no longer valid, correct link is
https://github.com/zendframework/zend-db/blob/release-2.5.2/src/Metadata/Metadata.php#L60

```php
throw new \Exception('cannot create source from adapter');
```

If the goal of #305 was to suppress this exception, wouldn't it be better to delete this line, instead of suppressing all exceptions?
