### ISSUE TITLE
Adding fields to a Service causes fields to be added multiple times

### ISSUE THREAD

**Issue by sariabod** [zfcampus/zf-apigility-admin#345]
Doing a fresh test install and just running composer update causes the adding of fields to a service to break. Composer.json is unedited from what the skeleton app provides. The list gets exponentially longer each time you add a field. The fields also get added again when you try to delete one of the fields.

The screenshot shows how the list grows with just a couple adds/deletes:

![apigility admin ui - chromium_065](https://cloud.githubusercontent.com/assets/1268903/17177800/d3ea55e8-53c7-11e6-84da-4b1318016058.png)

**Comment by netzfische** [comment]
Have the same error in a project since I did a composer update yesterday.
After I tried another update today I got the error described in #347.

**Comment by sariabod** [comment]
Thanks, this works, but only for base set up. As soon as you try to use other packages, you get errors. I bet it is just a transition issue. Once the ZF3 stuff is completed I think this issue will get resolved.

**Comment by weierophinney** [comment]
I've run into this now while testing changes to zf-apigility-admin and prepping the zf-apigility-skeleton pull request; working on identifying the root cause now, and will tag a new release when done.

Also discovered that current changes to zf-apigility-admin require changes to the UI code to ensure admin API URIs are created correctly.

I'll update this issue when I have a pull request and/or a new release with a fix.
