### ISSUE TITLE
RPC Controller __construct gives "Unable to fetch RPC services"

### ISSUE THREAD

**Issue by kimmo-steleco** [zfcampus/zf-apigility-admin#376]
Adding a __construct to a RPC controller causes the ui to give the "Unable to fetch RPC services" error and the RPC services names aren't in the list anymore. I can use them through postman just fine though.

_Using version: 1.5.9 installed with composer require of "zfcampus/zf-apigility"._

![apigility admin ui](https://cloud.githubusercontent.com/assets/24473858/25425218/7d9aca80-2a6b-11e7-9058-1198d0ee36e5.png)

**Comment by Tjalle** [comment]
Maybe a little late, but I had the same error today.

My issue was this :
I had copied my controller code because an other service was pretty much the same.
I missed the namespace (first line of php code in de controller file) and it was still set to the other service name.
This produced this error, after updating the namespace everything was working fina again.
